# 变量

## 获取对象属性：class

In [50]:
class(class(2))

[1] "character"

In [34]:
class('5')    #字符

[1] "character"

In [27]:
v = TRUE; r = FALSE
class(v)    #逻辑型
class(r)

[1] "logical"

[1] "logical"

In [35]:
class(2L)    #整型,L为整数
class(2.2L)    #数值型
class(2 + 3i)        #复数

[1] "integer"

[1] "numeric"

[1] "complex"

In [32]:
charToRaw("Hello")
class(charToRaw("Hello"))    #原型

[1] 48 65 6c 6c 6f

[1] "raw"

## 变量名

有效的变量名称由字母，数字和点或下划线字符组成。 变量名以字母或不以数字后跟的点开头

<img src = "pics/var_rule.jpg">

In [116]:
var.1 = c(0,1,2,3)  
var.2 = c("learn","R")   
c(TRUE,1) -> var.3  
paste(var.1, var.2, var.3)
cat(var.1, ',',  var.2, ',', var.3)

[1] "0 learn 1" "1 R 1"     "2 learn 1" "3 R 1"

0 1 2 3 , learn R , 1 1

# 数据结构

## 列表：List

其中包含许多不同类型的元素，如向量，函数甚至其中的另一个列表

In [77]:
lst = list(c(2,5,3),21.3,sin)
cat("直接展示lst：")
lst
cat('\n==================\n')
cat("print输出lst：\n\n")
print(lst)
cat('==================\n')
cat('lst类型：', class(lst))
cat('\n==================\n元素类型：')
paste(lst[1], "：\t", class(lst[1]))
paste(lst[2], "：\t", class(lst[2]))
paste(lst[3], "：\t", class(lst[3]))    #都是list

直接展示lst：

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
function (x)  .Primitive("sin")


print输出lst：

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
function (x)  .Primitive("sin")

lst类型： list
元素类型：

[1] "c(2, 5, 3) ：\t list"

[1] "21.3 ：\t list"

[1] ".Primitive(\"sin\") ：\t list"

## 向量：vector

In [110]:
c(1, 2, 3)
print(c(1, 2, 3))

[1] 1 2 3

[1] 1 2 3


In [36]:
class(c('1', 2, 3))
class(c(1, 2, 3))

[1] "character"

[1] "numeric"

## 矩阵:Matrix

矩阵是二维矩形数据集。 它可以使用矩阵函数的向量输入创建

In [107]:
M = matrix( c('a','a','b','c','b','a'), nrow = 2, ncol = 3, byrow = TRUE)
print(M)
M
class(M)

     [,1] [,2] [,3]
[1,] "a"  "a"  "b" 
[2,] "c"  "b"  "a" 


[,1] [,2] [,3]
[1,] a    a    b   
[2,] c    b    a

[1] "matrix"

## 数组：Array

数组函数使用一个dim属性创建所需的维数。 在下面的例子中，我们创建了一个包含两个元素的数组，每个元素为3x3个矩阵

In [106]:
a = array(c('green', 'yellow'), dim = c(3, 3, 2))
print(a)
a
class(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"



, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"

[1] "array"

## 因子：Factors

因子是使用向量创建的r对象。 它将向量与向量中元素的不同值一起存储为标签。 标签总是字符，不管它在输入向量中是数字还是字符或布尔等。 它们在统计建模中非常有用。
使用factor()函数创建因子。nlevels函数给出级别计数

In [105]:
colors = c('green','green','yellow','red','red','red','green')
factors <- factor(colors)
factors
cat("===================\n")
print(factors)
cat("===================\n")
nlevels(factors)
print(nlevels(factors))
class(factors)

[1] green  green  yellow red    red    red    green 
Levels: green red yellow

[1] green  green  yellow red    red    red    green 
Levels: green red yellow


[1] 3

[1] 3


[1] "factor"

## 数据帧：Data Frames

表格数据对象。 与数据帧中的矩阵不同，每列可以包含不同的数据模式。 第一列可以是数字，而第二列可以是字符，第三列可以是逻辑的。 它是等长度的向量的列表

In [104]:
BMI = data.frame(
   gender = c("Male", "Male","Female"), 
   height = c(152, 171.5, 165), 
   weight = c(81,93, 78),
   Age = c(42,38,26)
)
print(BMI)
BMI
class(BMI)

  gender height weight Age
1   Male  152.0     81  42
2   Male  171.5     93  38
3 Female  165.0     78  26


gender height weight Age
1 Male   152.0  81     42 
2 Male   171.5  93     38 
3 Female 165.0  78     26

[1] "data.frame"