# 变量

## 获取对象属性：class

In [50]:
class(class(2))

[1] "character"

In [34]:
class('5')    #字符

[1] "character"

In [27]:
v = TRUE; r = FALSE
class(v)    #逻辑型
class(r)

[1] "logical"

[1] "logical"

In [35]:
class(2L)    #整型,L为整数
class(2.2L)    #数值型
class(2 + 3i)        #复数

[1] "integer"

[1] "numeric"

[1] "complex"

In [32]:
charToRaw("Hello")
class(charToRaw("Hello"))    #原型

[1] 48 65 6c 6c 6f

[1] "raw"

## 变量名

有效的变量名称由字母，数字和点或下划线字符组成。 变量名以字母或不以数字后跟的点开头

<img src = "pics/var_rule.jpg">

In [2]:
var.1 = c(0,1,2,3)  
var.2 = c("learn","R")   
c(TRUE,1) -> var.3  
paste(var.1, var.2, var.3)
cat(var.1, ',',  var.2, ',', var.3)

[1] "0 learn 1" "1 R 1"     "2 learn 1" "3 R 1"

0 1 2 3 , learn R , 1 1

In [3]:
var_x <- "Hello"
cat("The class of var_x is ",class(var_x),"\n")
var_x <- 34.5
cat("  Now the class of var_x is ",class(var_x),"\n")
var_x <- 27L
cat("   Next the class of var_x becomes ",class(var_x),"\n")

The class of var_x is  character 
  Now the class of var_x is  numeric 
   Next the class of var_x becomes  integer 


### 查找变量

In [4]:
print(ls())
ls(pattern = "var")  #匹配给定变量名

[1] "var_x" "var.1" "var.2" "var.3"


[1] "var_x" "var.1" "var.2" "var.3"

以点(.)开头的变量被隐藏，它们可以使用ls()函数的“all.names = TRUE”参数列出。

In [6]:
print(ls(all.names = TRUE))

[1] ".pbd_env" "var_x"    "var.1"    "var.2"    "var.3"   


### 删除变量

In [7]:
rm(var.3)
print(var.3)

ERROR: Error in print(var.3): object 'var.3' not found


In [8]:
rm(list = ls())    #删除所有变量
print(ls())

character(0)


# 数据结构

## 列表：List

其中包含许多不同类型的元素，如向量，函数甚至其中的另一个列表

In [77]:
lst = list(c(2,5,3),21.3,sin)
cat("直接展示lst：")
lst
cat('\n==================\n')
cat("print输出lst：\n\n")
print(lst)
cat('==================\n')
cat('lst类型：', class(lst))
cat('\n==================\n元素类型：')
paste(lst[1], "：\t", class(lst[1]))
paste(lst[2], "：\t", class(lst[2]))
paste(lst[3], "：\t", class(lst[3]))    #都是list

直接展示lst：

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
function (x)  .Primitive("sin")


print输出lst：

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
function (x)  .Primitive("sin")

lst类型： list
元素类型：

[1] "c(2, 5, 3) ：\t list"

[1] "21.3 ：\t list"

[1] ".Primitive(\"sin\") ：\t list"

## 向量：vector

In [110]:
c(1, 2, 3)
print(c(1, 2, 3))

[1] 1 2 3

[1] 1 2 3


In [36]:
class(c('1', 2, 3))
class(c(1, 2, 3))

[1] "character"

[1] "numeric"

## 矩阵:Matrix

矩阵是二维矩形数据集。 它可以使用矩阵函数的向量输入创建

In [107]:
M = matrix( c('a','a','b','c','b','a'), nrow = 2, ncol = 3, byrow = TRUE)
print(M)
M
class(M)

     [,1] [,2] [,3]
[1,] "a"  "a"  "b" 
[2,] "c"  "b"  "a" 


[,1] [,2] [,3]
[1,] a    a    b   
[2,] c    b    a

[1] "matrix"

## 数组：Array

数组函数使用一个dim属性创建所需的维数。 在下面的例子中，我们创建了一个包含两个元素的数组，每个元素为3x3个矩阵

In [106]:
a = array(c('green', 'yellow'), dim = c(3, 3, 2))
print(a)
a
class(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"



, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"

[1] "array"

## 因子：Factors

因子是使用向量创建的r对象。 它将向量与向量中元素的不同值一起存储为标签。 标签总是字符，不管它在输入向量中是数字还是字符或布尔等。 它们在统计建模中非常有用。
使用factor()函数创建因子。nlevels函数给出级别计数

In [105]:
colors = c('green','green','yellow','red','red','red','green')
factors <- factor(colors)
factors
cat("===================\n")
print(factors)
cat("===================\n")
nlevels(factors)
print(nlevels(factors))
class(factors)

[1] green  green  yellow red    red    red    green 
Levels: green red yellow

[1] green  green  yellow red    red    red    green 
Levels: green red yellow


[1] 3

[1] 3


[1] "factor"

## 数据帧：Data Frames

表格数据对象。 与数据帧中的矩阵不同，每列可以包含不同的数据模式。 第一列可以是数字，而第二列可以是字符，第三列可以是逻辑的。 它是等长度的向量的列表

In [104]:
BMI = data.frame(
   gender = c("Male", "Male","Female"), 
   height = c(152, 171.5, 165), 
   weight = c(81,93, 78),
   Age = c(42,38,26)
)
print(BMI)
BMI
class(BMI)

  gender height weight Age
1   Male  152.0     81  42
2   Male  171.5     93  38
3 Female  165.0     78  26


gender height weight Age
1 Male   152.0  81     42 
2 Male   171.5  93     38 
3 Female 165.0  78     26

[1] "data.frame"

# 运算符

In [16]:
print(c(2, 5.5, 6) + c(2, 3))    #默认自动往后扩充
print(c(2, 5.5, 6) - c(2, 3))

Warning message in c(2, 5.5, 6) + c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 4.0 8.5 8.0


Warning message in c(2, 5.5, 6) - c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0.0 2.5 4.0


In [17]:
print(c(2, 5.5, 6) * c(2, 3, 1))

[1]  4.0 16.5  6.0


In [18]:
print(c(2, 5.5, 6) / c(2, 3, 4))

[1] 1.000000 1.833333 1.500000


In [19]:
print(c(2, 5.5, 6) %% c(2, 3, 4))    #求余

[1] 0.0 2.5 2.0


In [20]:
print(c(2, 5.5, 6) %/% c(2, 3, 4))    #求商数

[1] 1 1 1


In [21]:
print(c(2, 5.5, 6) ^ c(2, 3, 1))

[1]   4.000 166.375   6.000


In [24]:
print(c(2, 5.5, 6) > c(2, 3, 1))
print(c(2, 5.5) < c(2, 3, 6))

[1] FALSE  TRUE  TRUE


Warning message in c(2, 5.5) < c(2, 3, 6):
“longer object length is not a multiple of shorter object length”

[1] FALSE FALSE  TRUE


## 逻辑运算符

In [26]:
print(c(3,1,TRUE,2+3i) & c(4,1,FALSE,2+3i))
print(c(3,1,TRUE,2+3i) | c(4,1,FALSE,2+3i))
print(!c(3,1,FALSE,2+3i))

[1]  TRUE  TRUE FALSE  TRUE
[1] TRUE TRUE TRUE TRUE
[1] FALSE FALSE  TRUE FALSE


### 标量运算

In [28]:
c(3,1,TRUE,2+3i) && c(4,1,FALSE,2+3i)    #只取第一个元素
c(0,1,TRUE,2+3i) || c(0,1,FALSE,2+3i)

[1] TRUE

[1] FALSE

### 生成序列

In [34]:
v = 2 : 8
print(v)
paste(class(v), class(c(2 : 8)))
print(v == c(2:8))

[1] 2 3 4 5 6 7 8


[1] "integer integer"

[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE


In [36]:
print(2 %in% c(1 : 9))

[1] TRUE
