In [11]:
from scipy.spatial.distance import pdist    #成对距离
from scipy.spatial.distance import cdist    #成对数组距离

[pdist](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html#scipy.spatial.distance.pdist):n维空间中观测值的成对距离；
[cdist](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html#scipy.spatial.distance.cdist):计算两组输入的每对之间的距离。

In [2]:
from scipy.spatial import distance

In [8]:
print(distance.cosine([1, 1, 1], [2, 5, 3], w = [0.2, 0.4, 0.4]))
pdist([[1, 1, 1], [2, 5, 3]], 'cosine')    #余弦距离

0.026271008879704683


array([0.03509872])

In [9]:
distance.chebyshev([1, 0, 0], [0, 3, 0])    #切比雪夫距离

3

In [12]:
'''四个二维坐标之间的欧几里德距离'''
coords = [(35.0456, -85.2672), (35.1174, -89.9711), (35.9728, -83.9422), (36.1667, -86.7833)]
cdist(coords, coords, 'euclidean')

array([[0.        , 4.70444794, 1.6171966 , 1.88558331],
       [4.70444794, 0.        , 6.0892811 , 3.35605413],
       [1.6171966 , 6.0892811 , 0.        , 2.84770898],
       [1.88558331, 3.35605413, 2.84770898, 0.        ]])

In [13]:
'''三维点到单位立方体角落的曼哈顿距离'''
import numpy as np
a = np.array([[0, 0, 0],
              [0, 0, 1],
              [0, 1, 0],
              [0, 1, 1],
              [1, 0, 0],
              [1, 0, 1],
              [1, 1, 0],
              [1, 1, 1]])

b = np.array([[ 0.1,  0.2,  0.4]])

cdist(a, b, 'cityblock')

array([[0.7],
       [0.9],
       [1.3],
       [1.5],
       [1.5],
       [1.7],
       [2.1],
       [2.3]])

[马氏距离](https://blog.csdn.net/bbbeoy/article/details/78617680)

In [17]:
x=np.random.random(10)
y=np.random.random(10)

#马氏距离要求样本数要大于维数，否则无法求协方差矩阵
#此处进行转置，表示10个样本，每个样本2维
X=np.vstack([x,y])
XT=X.T

pdist(XT,'mahalanobis')

array([0.77954668, 1.29641616, 1.93655732, 3.19820149, 1.42004906,
       2.75519389, 2.69222929, 3.30500306, 2.79028109, 0.80857745,
       1.16396493, 2.54254633, 0.72901016, 2.08473549, 2.15895462,
       2.55369947, 2.14153709, 1.30268122, 1.91928265, 0.41934528,
       1.49394948, 1.40318992, 2.65474314, 2.53082265, 1.94729385,
       0.88376258, 1.51955028, 1.95009438, 1.40918641, 1.26043199,
       1.81431793, 0.46156546, 0.78301128, 2.34857469, 2.91094418,
       1.35806441, 1.4646383 , 2.24314963, 2.1208306 , 0.67571248,
       2.12654785, 2.56876004, 2.7764032 , 3.12113901, 0.96225754])